
export const PRUEBA = 'PRUEBA'
export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_CLIENT_BY_NAME = "GET_CLIENT_BY_NAME"
export const GET_WALKER_BY_NAME = "GET_WALKER_BY_NAME"
export const RESTORE_CLIENTS = "RESTORE_CLIENTS"
export const RESTORE_WALKERS = "RESTORE_WALKERS"

export const CREATE_USER = 'CREATE_USER'
// export const GET_ALL_USERS = 'GET_ALL_USERS'
export const EDIT_USER = 'EDIT_USER'