
export const PRUEBA = 'PRUEBA'
export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_CLIENT_BY_NAME = "GET_CLIENT_BY_NAME"
export const GET_WALKER_BY_NAME = "GET_WALKER_BY_NAME"
export const RESTORE_CLIENTS = "RESTORE_CLIENTS"
export const RESTORE_WALKERS = "RESTORE_WALKERS"
export const ORDER_DEFAULT = "ORDER_DEFAULT"
export const FILTER_WALKERS = "FILTER_WALKERS"
export const CREATE_USER = 'CREATE_USER'
export const EDIT_USER = 'EDIT_USER'
export const CURRENT_USER = 'CURRENT_USER'
export const CREATE_DOG = 'CREATE_DOG'
export const SET_WALK = 'SET_WALK'
